### ISSUE TITLE
Request: TPM site model

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/babette#17]
```
	Model 		f(a) 	f(c) 	f(g) 	f(t) 	kappa 	titv 	Ra	Rb	Rc	Rd	Re	Rf	pInv 	gamma
----------------------------------------------------------------------------------------------------------------------------------------
AIC 	TPM2uf+I+G	0.41	0.20	0.13	0.25	0.00	0.00	  0.488   7.746   0.488   1.000   7.746   1.000    0.61	   3.08
 ```

> Nu zou ik dus graag een TPM2uf+I+G model willen gebruiken voor mijn COI alignment.
> Ik kende dit model nog niet (eerder gebruikte ik gewoon een algemeen GTR model), maar vond dit erover http://www.iqtree.org/doc/Substitution-Models.
> Typisch aan dit model is, dat bepaalde frequenties gelijk worden gesteld aan elkaar: AC=AT, AG=CT, CG=GT and equal base freq.   
> Is het mogelijk om dit te doen mbv babette? Of uberhaupt in BEAUti, dat jij weet? 
> Begin ik met "create_gtr_site_model()" om dan vervolgens daar details op te geven van frequenties van substituties?
> Ik neem aan dat als ik dat doe door de waarden uit de vet gedrukte rij hierboven simpelweg over te nemen, dit alleen startwaarden zijn voor de MCMC run?

**Comment by richelbilderbeek** [comment]
> [translated] is it possible to use a TPM2 site model within babette or BEAUti?

TLDR: No. 

The TPM nucleotide substitution model is not supported by `babette`. It is not supported by BEAUti either. There may be plug-in for this site model, but I estimate the chance of its existence at 1%.

`+I` denotes 'allowing for a proportion of invariable sites.'  , which is supported.

`+G` denotes 'discrete Gamma model (Yang, 1994) with default 4 rate categories. The number of categories can be changed with e.g. +G8.', which is supported.

> [translated] if I do [...]

TLDR: Sorry, will not work

With `create_gtr_site_model` it is impossible to set nucleotide-pair frequencies. One can set the single nucleotide frequencies as shown in the jModelTest2 results and one can set the rates, but this results in a model with a higher AIC.  

What would work, is to use the next model recommended by jModelTest2.

**Comment by KPHendriks** [comment]
Thanks for the fast reply, Richel. I will post any future questions around here. :-)
Cheers!

**Comment by richelbilderbeek** [comment]
Good luck and thanks!
