### ISSUE TITLE
BEAUti reports an error with two alignments option from babette: "IDs should be unique"

### ISSUE THREAD

**Issue by KPHendriks** [richelbilderbeek/babette#18]
Dear Richel,

I created a BEAST2 input file as follows:
create_beast2_input_file(input_filenames = c(input_Plectostoma_COI,input_Plectostoma_ITS1),
                         output_filename = output_Plectostoma_all_markers_combined)

No error message.

When I open in BEAUti I get this error message, suggesting a duplicate sequence name. But this 'duplicate' is from two different alignments. 

![image](https://user-images.githubusercontent.com/23340933/41730952-65fc48c8-757d-11e8-97a0-ad4c4482c5e1.png)

What can I have done wrong?
Thanks!

**Comment by richelbilderbeek** [comment]
No reply, so no use case. Will close this Issue,
